create Hw02 express
Zina88/nodejs-homework-rest-api pull request #2
Opened 2022-12-12 06:21 UTC by Zina88

2022-12-12 17:31 UTC, BohdanGres requested changes
все добре, спробуй зробити олну універсальну мідлварку для перевірки боді + додай ще схожу але вже для перевірки req.params і навісь на роути в яких щось прилітає в них

2022-12-12 17:31 UTC, BohdanGres commented on middlewares/validateBody.js
> +const validateBody = (schema) => {
validateBody і validateBodyUpdate майже однакові, спробуй зробити одну універсальну мідлварку

2022-12-13 08:15 UTC, Zina88 commented
middlewarе зробила однією функцією, але не зовсім зрозуміла щодо req.params

2022-12-13 16:22 UTC, BohdanGres approved these changes
все добре зробила, що до req.params я мав на увазі зробити мідлвар для валідації данних в ньому по аналогі з мідлваром для боді. Можеш зробити в некст домашці

2022-12-13 16:44 UTC, merged